version: "3.9"
services:
  api:
    build: ./apps/api
    ports:
      - "3000:3000"

  web:
    build: ./apps/web
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000
